- name: gamemode
  type: integer
  label: Mode
  default: 1
  values:
    - label: Survival
      value: 0
      description: "Search for resources, crafting, gain levels, health and hunger"
    - label: Creative
      value: 1
      description: "Unlimited resources, free flying and destroy blocks instantly"
    - label: Adventure
      value: 2
      description: "Explorers only, cannot place or destroy blocks"

- name: level-seed
  type: string
  label: Map Seed

- name: level-type
  type: string
  label: Level type
  default: DEFAULT
  values:
    - label: Default
      value: DEFAULT
      description: "Standard world with hills, valleys, water etc."
    - label: Flat
      value: FLAT
      description: "A flat world with no features, meant for building"
    - label: Large Biomes
      value: LARGEBIOMES
      description: "Same as default but all biomes are larger"

- name: difficulty
  type: integer
  label: Difficulty
  default: 1
  values:
    - label: Peaceful
      value: 0
    - label: Easy
      value: 1
    - label: Normal
      value: 2
    - label: Hard
      value: 3

- name: allow-flight
  type: boolean
  label: Allow flight
  default: false

- name: allow-nether
  type: boolean
  label: Allow nether
  default: true

- name: generate-structures
  type: boolean
  label: Generate structures
  default: true

- name: enable-command-block
  type: boolean
  label: Enable command blocks
  default: false

- name: pvp
  type: boolean
  label: Spawn NPCs
  default: true

- name: spawn-animals
  type: boolean
  label: Spawn animals
  default: true

- name: spawn-monsers
  type: boolean
  label: Spawn monsters
  default: true

- name: spawn-npcs
  type: boolean
  label: Spawn NPCs
  default: true

- name: texture-pack
  type: string
  label: Texture Pack URL

